### ISSUE TITLE
Bug when starting game

### ISSUE THREAD

**Issue by VictorLlanir** [Gamesflow/2048-game#8]
When I access the game, the three options below are enabled, but the music do not play unless I disable and enable it again.
![image](https://user-images.githubusercontent.com/28709418/136104025-f2cf5163-57a5-468d-aae5-4ff5c8439fb4.png)

**Comment by coderGtm** [comment]
That is due to browser restrictions on playing sound. The browser does not allow any webpage to play sound until a user interacts with a website, for a good ux. When you toggle the switch, you are essentially making the first interaction with the website and hence, from then on you can hear the sound playing.
